-- 1. Create Donors Table
CREATE TABLE Donors (
    Donor_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Gender CHAR(1) CHECK (Gender IN ('M', 'F')),
    Birth_Date DATE NOT NULL,
    Phone VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Last_Donation_Date DATE
);

-- 2. Create Blood Units Table
CREATE TABLE Blood_Units (
    Unit_Barcode_ID VARCHAR2(20) PRIMARY KEY,
    Donor_ID NUMBER,
    Blood_Group VARCHAR2(5) NOT NULL,
    Collection_Date DATE DEFAULT SYSDATE,
    Expiration_Date DATE NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Pending Test',
    CONSTRAINT fk_bu_donor FOREIGN KEY (Donor_ID) REFERENCES Donors(Donor_ID) ON DELETE SET NULL,
    CONSTRAINT chk_bu_status CHECK (Status IN ('Pending Test', 'Available', 'Reserved', 'Dispatched', 'Utilized', 'Discarded'))
);

-- 3. Create Lab Tests Table
CREATE TABLE Lab_Tests (
    Test_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Unit_Barcode_ID VARCHAR2(20) NOT NULL,
    HIV_Result VARCHAR2(10) CHECK (HIV_Result IN ('Negative', 'Positive')),
    Hepatitis_B_Result VARCHAR2(10) CHECK (Hepatitis_B_Result IN ('Negative', 'Positive')),
    Hepatitis_C_Result VARCHAR2(10) CHECK (Hepatitis_C_Result IN ('Negative', 'Positive')),
    Syphilis_Result VARCHAR2(10) CHECK (Syphilis_Result IN ('Negative', 'Positive')),
    Test_Date DATE DEFAULT SYSDATE,
    Overall_Safety VARCHAR2(10) CHECK (Overall_Safety IN ('Safe', 'Unsafe')),
    CONSTRAINT fk_lt_unit FOREIGN KEY (Unit_Barcode_ID) REFERENCES Blood_Units(Unit_Barcode_ID) ON DELETE CASCADE
);

-- 4. Create Hospitals Table
CREATE TABLE Hospitals (
    Hospital_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Hospital_Name VARCHAR2(100) NOT NULL,
    Location VARCHAR2(150),
    Contact_Phone VARCHAR2(20) NOT NULL
);

-- 5. Create Blood Requests Table
CREATE TABLE Blood_Requests (
    Request_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Hospital_ID NUMBER NOT NULL,
    Required_Blood_Group VARCHAR2(5) NOT NULL,
    Requested_Quantity NUMBER NOT NULL CHECK (Requested_Quantity > 0),
    Request_Date DATE DEFAULT SYSDATE,
    Urgency_Level VARCHAR2(10) CHECK (Urgency_Level IN ('Routine', 'Urgent', 'Emergency')),
    Request_Status VARCHAR2(20) DEFAULT 'Pending' CHECK (Request_Status IN ('Pending', 'Approved', 'Fulfilled', 'Cancelled')),
    CONSTRAINT fk_br_hospital FOREIGN KEY (Hospital_ID) REFERENCES Hospitals(Hospital_ID) ON DELETE CASCADE
);

-- 6. Create Dispatches Table
CREATE TABLE Dispatches (
    Dispatch_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Request_ID NUMBER NOT NULL,
    Unit_Barcode_ID VARCHAR2(20) NOT NULL,
    Dispatch_Date DATE DEFAULT SYSDATE,
    Delivery_Manifest_No VARCHAR2(30) UNIQUE NOT NULL,
    CONSTRAINT fk_disp_req FOREIGN KEY (Request_ID) REFERENCES Blood_Requests(Request_ID) ON DELETE CASCADE,
    CONSTRAINT fk_disp_unit FOREIGN KEY (Unit_Barcode_ID) REFERENCES Blood_Units(Unit_Barcode_ID) ON DELETE CASCADE
);

-- INSERT SAMPLES

INSERT INTO Donors (First_Name, Last_Name, Gender, Birth_Date, Phone, Email, Last_Donation_Date)
VALUES ('John', 'Doe', 'M', TO_DATE('1990-05-15', 'YYYY-MM-DD'), '+250788111222', 'john.doe@email.com', TO_DATE('2026-01-10', 'YYYY-MM-DD'));

INSERT INTO Donors (First_Name, Last_Name, Gender, Birth_Date, Phone, Email, Last_Donation_Date)
VALUES ('Jane', 'Smith', 'F', TO_DATE('1995-08-22', 'YYYY-MM-DD'), '+250788333444', 'jane.smith@email.com', TO_DATE('2026-02-14', 'YYYY-MM-DD'));

INSERT INTO Blood_Units (Unit_Barcode_ID, Donor_ID, Blood_Group, Collection_Date, Expiration_Date, Status)
VALUES ('BB00012345', 1, 'O+', TO_DATE('2026-07-01', 'YYYY-MM-DD'), TO_DATE('2026-08-12', 'YYYY-MM-DD'), 'Available');

INSERT INTO Blood_Units (Unit_Barcode_ID, Donor_ID, Blood_Group, Collection_Date, Expiration_Date, Status)
VALUES ('BB00012346', 2, 'A-', TO_DATE('2026-07-02', 'YYYY-MM-DD'), TO_DATE('2026-08-13', 'YYYY-MM-DD'), 'Pending Test');

INSERT INTO Lab_Tests (Unit_Barcode_ID, HIV_Result, Hepatitis_B_Result, Hepatitis_C_Result, Syphilis_Result, Test_Date, Overall_Safety)
VALUES ('BB00012345', 'Negative', 'Negative', 'Negative', 'Negative', TO_DATE('2026-07-02', 'YYYY-MM-DD'), 'Safe');

INSERT INTO Hospitals (Hospital_Name, Location, Contact_Phone)
VALUES ('King Faisal Hospital', 'Kigali, Gasabo', '+250790000111');

INSERT INTO Hospitals (Hospital_Name, Location, Contact_Phone)
VALUES ('CHUK Medical Center', 'Kigali, Nyarugenge', '+250790000222');

INSERT INTO Blood_Requests (Hospital_ID, Required_Blood_Group, Requested_Quantity, Request_Date, Urgency_Level, Request_Status)
VALUES (1, 'O+', 1, TO_DATE('2026-07-05', 'YYYY-MM-DD'), 'Emergency', 'Pending');

COMMIT;
