-- =============================================================================
-- FILE 3: ADVANCED DATABASE PROGRAMMING (TRIGGERS & AUDIT SYSTEM)
-- SCHEMA: U310482025_SALAH_SBB_DB
-- =============================================================================

SET FEEDBACK ON;
SET SERVEROUTPUT ON;

PROMPT -------------------------------------------------------------------------
PROMPT 1. CREATING AUDIT AND HOLIDAY REFERENCE TABLES
PROMPT -------------------------------------------------------------------------

-- Create System Audit Table to track DML activities
CREATE TABLE Blood_Bank_Audit (
    Audit_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DB_User VARCHAR2(50) DEFAULT USER,
    Action_Type VARCHAR2(20),
    Table_Name VARCHAR2(30),
    Action_Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Public Holidays Reference Table as required by business rules
CREATE TABLE Public_Holidays (
    Holiday_Date DATE PRIMARY KEY,
    Holiday_Name VARCHAR2(100) NOT NULL
);

-- Insert Sample Holidays for testing (e.g., New Year, Independence Day)
INSERT INTO Public_Holidays (Holiday_Date, Holiday_Name) VALUES (TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'New Year');
INSERT INTO Public_Holidays (Holiday_Date, Holiday_Name) VALUES (TO_DATE('2026-07-01', 'YYYY-MM-DD'), 'Independence Day');
COMMIT;


PROMPT -------------------------------------------------------------------------
PROMPT 2. IMPLEMENTING SECURITY RESTRICTION TRIGGER (BUSINESS RULE)
PROMPT -------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER trg_security_restriction
BEFORE INSERT OR UPDATE OR DELETE ON Blood_Units
DECLARE
    v_holiday_count NUMBER;
    v_day_name VARCHAR2(20);
BEGIN
    -- Get current day name
    v_day_name := RTRIM(TO_CHAR(SYSDATE, 'DAY'));

    -- Check if today is registered as a public holiday
    SELECT COUNT(*) INTO v_holiday_count
    FROM Public_Holidays
    WHERE TRUNC(Holiday_Date) = TRUNC(SYSDATE);

    -- Enforce strict business rule restriction (Example: Block during weekends or holidays)
    -- You can modify 'SATURDAY' or 'SUNDAY' based on your regional academic constraints
    IF v_day_name IN ('SATURDAY', 'SUNDAY') OR v_holiday_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Security Violation: Data modifications on Blood Units are prohibited during weekends and public holidays.');
    END IF;
END;
/


PROMPT -------------------------------------------------------------------------
PROMPT 3. IMPLEMENTING AUDIT TRACKING TRIGGER
PROMPT -------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER trg_blood_units_audit
AFTER INSERT OR UPDATE OR DELETE ON Blood_Units
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    -- Detect the type of DML execution dynamically
    IF INSERTING THEN
        v_action := 'INSERT';
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
    ELSIF DELETING THEN
        v_action := 'DELETE';
    END IF;

    -- Record the transaction details into the audit logs
    INSERT INTO Blood_Bank_Audit (DB_User, Action_Type, Table_Name, Action_Timestamp)
    VALUES (USER, v_action, 'BLOOD_UNITS', CURRENT_TIMESTAMP);
END;
/
